global using BaseUISupport.Controls;
global using BaseUISupport.Converters;
global using BaseUISupport.Helpers;
global using BaseUISupport.Settings;
global using CasparLauncher.CasparCG;
global using CasparLauncher.CasparCG.Configuration;
global using CasparLauncher.CasparCG.Configuration.Consumers;
global using CasparLauncher.CasparCG.Configuration.Enums;
global using CasparLauncher.Launcher;
global using Microsoft.Win32;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Data;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;

// Aliases
global using MessageBox = BaseUISupport.Controls.MessageBox;
global using L = CasparLauncher.Properties.Resources;
global using S = BaseUISupport.Settings.SettingStore;
global using Timer = System.Timers.Timer;
global using WF = System.Windows.Forms;