//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasparLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasparLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del servidor.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida Bluefish.
        /// </summary>
        public static string BluefishConsumer {
            get {
                return ResourceManager.GetString("BluefishConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examinar....
        /// </summary>
        public static string BrowseForFileButton {
            get {
                return ResourceManager.GetString("BrowseForFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir carpeta....
        /// </summary>
        public static string BrowseForPathButton {
            get {
                return ResourceManager.GetString("BrowseForPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar aplicación.
        /// </summary>
        public static string ClosePromptCaption {
            get {
                return ResourceManager.GetString("ClosePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta aplicación controla el correcto funcionamiento de los componentes del servidor. Al cerrarla se detendrán todos los servicios.
        ///¿Desea continuar?.
        /// </summary>
        public static string ClosePromptMessage {
            get {
                return ResourceManager.GetString("ClosePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líneas de consola.
        /// </summary>
        public static string ConfigBufferLines {
            get {
                return ResourceManager.GetString("ConfigBufferLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de configuración.
        /// </summary>
        public static string ConfigFileDialogFilterDescription {
            get {
                return ResourceManager.GetString("ConfigFileDialogFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo de configuración.
        /// </summary>
        public static string ConfigFileText {
            get {
                return ResourceManager.GetString("ConfigFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir al inicio.
        /// </summary>
        public static string ConfigOpenAtLogin {
            get {
                return ResourceManager.GetString("ConfigOpenAtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string ConfigTabAboutGb {
            get {
                return ResourceManager.GetString("ConfigTabAboutGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CasparCG Server es un software para Windows y Linux utilizado para la reproducción profesional de gráficos, audio y video a múltiples salidas, como un compositor en tiempo real basado en capas. Ha estado en uso ininterrumpido en transmisiones desde el 2006 y lo mejor, es libre. Usado por la mayoría de los canales de Europa.
        ///Más información en:.
        /// </summary>
        public static string ConfigTabAboutProjectDescription {
            get {
                return ResourceManager.GetString("ConfigTabAboutProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto CasparCG.
        /// </summary>
        public static string ConfigTabAboutProjectName {
            get {
                return ResourceManager.GetString("ConfigTabAboutProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutables.
        /// </summary>
        public static string ConfigTabExecGbHeader {
            get {
                return ResourceManager.GetString("ConfigTabExecGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forzar idioma.
        /// </summary>
        public static string ConfigTabLangValue {
            get {
                return ResourceManager.GetString("ConfigTabLangValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string ConfigTabOptionsCbHead {
            get {
                return ResourceManager.GetString("ConfigTabOptionsCbHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración del servidor.
        /// </summary>
        public static string ConfigTabServerConfigHeader {
            get {
                return ResourceManager.GetString("ConfigTabServerConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo.
        /// </summary>
        public static string ConfigWindowChannelsBfDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Embeber audio.
        /// </summary>
        public static string ConfigWindowChannelsBfEmbedAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfEmbedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyer.
        /// </summary>
        public static string ConfigWindowChannelsBfKeyer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfKeyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio de keyer interno.
        /// </summary>
        public static string ConfigWindowChannelsBfKeyerAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfKeyerAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flujo SDI.
        /// </summary>
        public static string ConfigWindowChannelsBfSdiStream {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfSdiStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watchdog.
        /// </summary>
        public static string ConfigWindowChannelsBfWatchdog {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración del canal.
        /// </summary>
        public static string ConfigWindowChannelsChannelConfigGbHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelConfigGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canal {0}.
        /// </summary>
        public static string ConfigWindowChannelsChannelListItemDisplay {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelListItemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canales.
        /// </summary>
        public static string ConfigWindowChannelsChannels {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de video.
        /// </summary>
        public static string ConfigWindowChannelsChannelVideoMode {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración de la salida.
        /// </summary>
        public static string ConfigWindowChannelsConsumerConfigGbHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerConfigGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas.
        /// </summary>
        public static string ConfigWindowChannelsConsumers {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño del buffer.
        /// </summary>
        public static string ConfigWindowChannelsDlBuffer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo.
        /// </summary>
        public static string ConfigWindowChannelsDlDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Embeber audio.
        /// </summary>
        public static string ConfigWindowChannelsDlEmbedAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlEmbedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo de alfa.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyer.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo alfa.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latencia.
        /// </summary>
        public static string ConfigWindowChannelsDlLatency {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumentos.
        /// </summary>
        public static string ConfigWindowChannelsFfArgs {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsFfArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta.
        /// </summary>
        public static string ConfigWindowChannelsFfPath {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsFfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canales.
        /// </summary>
        public static string ConfigWindowChannelsHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta salida no tiene opciones configurables.
        /// </summary>
        public static string ConfigWindowChannelsNiNoOptions {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNiNoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitar campos.
        /// </summary>
        public static string ConfigWindowChannelsNnAllowFields {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNnAllowFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string ConfigWindowChannelsNnName {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canales.
        /// </summary>
        public static string ConfigWindowChannelsSaChannelLayout {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsSaChannelLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latencia.
        /// </summary>
        public static string ConfigWindowChannelsSaLatency {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsSaLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siempre encima.
        /// </summary>
        public static string ConfigWindowChannelsScAlwaysOn {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScAlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de aspecto.
        /// </summary>
        public static string ConfigWindowChannelsScAspect {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin bordes.
        /// </summary>
        public static string ConfigWindowChannelsScBorderless {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio de color.
        /// </summary>
        public static string ConfigWindowChannelsScColourSpace {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScColourSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo.
        /// </summary>
        public static string ConfigWindowChannelsScDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alto.
        /// </summary>
        public static string ConfigWindowChannelsScHeight {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interactiva.
        /// </summary>
        public static string ConfigWindowChannelsScInteractive {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo alfa.
        /// </summary>
        public static string ConfigWindowChannelsScKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alfa lado a lado.
        /// </summary>
        public static string ConfigWindowChannelsScSbsKey {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScSbsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estirar.
        /// </summary>
        public static string ConfigWindowChannelsScStretch {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vsync.
        /// </summary>
        public static string ConfigWindowChannelsScVsync {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScVsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ancho.
        /// </summary>
        public static string ConfigWindowChannelsScWidth {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo ventana.
        /// </summary>
        public static string ConfigWindowChannelsScWindowed {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición X.
        /// </summary>
        public static string ConfigWindowChannelsScX {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición Y.
        /// </summary>
        public static string ConfigWindowChannelsScY {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMCP.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección escáner de medios.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpMediaHost {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpMediaHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto escáner de medios.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpMediaPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpMediaPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño del buffer.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashBuffer {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flash.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones del servidor.
        /// </summary>
        public static string ConfigWindowOptionsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto de depuración.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlDebugPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlDebugPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitar GPU.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlEnableGpu {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlEnableGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HTML.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string ConfigWindowOptionsTabLogGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string ConfigWindowOptionsTabLogLogLevel {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga automática.
        /// </summary>
        public static string ConfigWindowOptionsTabNdiAutoload {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabNdiAutoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NDI.
        /// </summary>
        public static string ConfigWindowOptionsTabNdiGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabNdiGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshabilitar clientes AMCP.
        /// </summary>
        public static string ConfigWindowOptionsTabOscAmcpDisable {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscAmcpDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto por defecto.
        /// </summary>
        public static string ConfigWindowOptionsTabOscDefaultPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscDefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OSC.
        /// </summary>
        public static string ConfigWindowOptionsTabOscGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredClientAddress {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredClientPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredClientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes predefinidos.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredefinedClients {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredefinedClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de seguridad.
        /// </summary>
        public static string ConfigWindowOptionsTabPassGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPassGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string ConfigWindowOptionsTabPassValue {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPassValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de datos.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsDataPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rutas.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de registro.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsLogPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de medios.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsMediaPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsMediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de plantillas.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsTemplatePath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string ConfigWindowSaveButton {
            get {
                return ResourceManager.GetString("ConfigWindowSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar configuración del servidor.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar servidor.
        /// </summary>
        public static string ContextMenuCasparItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuCasparItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir ventana de diagnóstico.
        /// </summary>
        public static string ContextMenuDiagItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuDiagItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string ContextMenuExitItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExitItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reconstruir medios.
        /// </summary>
        public static string ContextMenuRebuildMediaDbItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuRebuildMediaDbItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar escáner de medios.
        /// </summary>
        public static string ContextMenuScannerItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuScannerItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida Decklink.
        /// </summary>
        public static string DecklinkConsumer {
            get {
                return ResourceManager.GetString("DecklinkConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar ejecutable.
        /// </summary>
        public static string DeleteExecutablePromptCaption {
            get {
                return ResourceManager.GetString("DeleteExecutablePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguro desea eliminar el ejecutable? (no se puede deshacer).
        /// </summary>
        public static string DeleteExecutablePromptMessage {
            get {
                return ResourceManager.GetString("DeleteExecutablePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumentos.
        /// </summary>
        public static string ExecutableConfigWindowArgs {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoejecutar.
        /// </summary>
        public static string ExecutableConfigWindowAuto {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutar automáticamente al iniciar la aplicación.
        /// </summary>
        public static string ExecutableConfigWindowAutoDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowAutoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comandos de inicio.
        /// </summary>
        public static string ExecutableConfigWindowCommands {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retardo entre comandos.
        /// </summary>
        public static string ExecutableConfigWindowCommandsDelay {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de pausa entre cada comando de inicio (milisegundos).
        /// </summary>
        public static string ExecutableConfigWindowCommandsDelayDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comando.
        /// </summary>
        public static string ExecutableConfigWindowCommandsDgHeader {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitar comandos.
        /// </summary>
        public static string ExecutableConfigWindowCommandsEnabled {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilita el envío de comandos al ejecutable en la consola.
        /// </summary>
        public static string ExecutableConfigWindowCommandsEnabledDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retardo de inicio.
        /// </summary>
        public static string ExecutableConfigWindowDelay {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera antes de la ejecución (milisegundos).
        /// </summary>
        public static string ExecutableConfigWindowDelayDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string ExecutableConfigWindowName {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta del ejecutable.
        /// </summary>
        public static string ExecutableConfigWindowPath {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración del ejecutable.
        /// </summary>
        public static string ExecutableConfigWindowTitle {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación del ejecutable incorrecta.
        /// </summary>
        public static string ExecutableNotFoundWarningCaption {
            get {
                return ResourceManager.GetString("ExecutableNotFoundWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compruebe la ruta del ejecutable.
        /// </summary>
        public static string ExecutableNotFoundWarningMessage {
            get {
                return ResourceManager.GetString("ExecutableNotFoundWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida FFmpeg.
        /// </summary>
        public static string FFConsumer {
            get {
                return ResourceManager.GetString("FFConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutables.
        /// </summary>
        public static string FileDialogFilterDescription {
            get {
                return ResourceManager.GetString("FileDialogFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida iVGA.
        /// </summary>
        public static string IvgaConsumer {
            get {
                return ResourceManager.GetString("IvgaConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida NDI.
        /// </summary>
        public static string NdiConsumer {
            get {
                return ResourceManager.GetString("NdiConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo ejecutable.
        /// </summary>
        public static string NewExecutableName {
            get {
                return ResourceManager.GetString("NewExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar archivo.
        /// </summary>
        public static string OpenConfigEditorEditButtonText {
            get {
                return ResourceManager.GetString("OpenConfigEditorEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo archivo.
        /// </summary>
        public static string OpenConfigEditorNewButtonText {
            get {
                return ResourceManager.GetString("OpenConfigEditorNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida a Pantalla.
        /// </summary>
        public static string ScreenConsumer {
            get {
                return ResourceManager.GetString("ScreenConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string StatusTabHeader {
            get {
                return ResourceManager.GetString("StatusTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida a Audio de Sistema.
        /// </summary>
        public static string SystemAudioConsumer {
            get {
                return ResourceManager.GetString("SystemAudioConsumer", resourceCulture);
            }
        }
    }
}
