//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasparLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasparLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del servidor.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida Bluefish.
        /// </summary>
        public static string BluefishConsumer {
            get {
                return ResourceManager.GetString("BluefishConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinar....
        /// </summary>
        public static string BrowseForFileButton {
            get {
                return ResourceManager.GetString("BrowseForFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir carpeta....
        /// </summary>
        public static string BrowseForPathButton {
            get {
                return ResourceManager.GetString("BrowseForPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar aplicación.
        /// </summary>
        public static string ClosePromptCaption {
            get {
                return ResourceManager.GetString("ClosePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta aplicación controla el correcto funcionamiento de los componentes del servidor. Al cerrarla se detendrán todos los servicios.
        ///¿Desea continuar?.
        /// </summary>
        public static string ClosePromptMessage {
            get {
                return ResourceManager.GetString("ClosePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líneas de consola.
        /// </summary>
        public static string ConfigBufferLines {
            get {
                return ResourceManager.GetString("ConfigBufferLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de configuración.
        /// </summary>
        public static string ConfigFileDialogFilterDescription {
            get {
                return ResourceManager.GetString("ConfigFileDialogFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo de configuración.
        /// </summary>
        public static string ConfigFileText {
            get {
                return ResourceManager.GetString("ConfigFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir al inicio.
        /// </summary>
        public static string ConfigOpenAtLogin {
            get {
                return ResourceManager.GetString("ConfigOpenAtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string ConfigTabAboutGb {
            get {
                return ResourceManager.GetString("ConfigTabAboutGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CasparCG Server es un software para Windows y Linux utilizado para la reproducción profesional de gráficos, audio y video a múltiples salidas, como un compositor en tiempo real basado en capas. Ha estado en uso ininterrumpido en transmisiones desde el 2006 y lo mejor, es libre. Usado por la mayoría de los canales de Europa.
        ///Más información en:.
        /// </summary>
        public static string ConfigTabAboutProjectDescription {
            get {
                return ResourceManager.GetString("ConfigTabAboutProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto CasparCG.
        /// </summary>
        public static string ConfigTabAboutProjectName {
            get {
                return ResourceManager.GetString("ConfigTabAboutProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutables.
        /// </summary>
        public static string ConfigTabExecGbHeader {
            get {
                return ResourceManager.GetString("ConfigTabExecGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forzar idioma.
        /// </summary>
        public static string ConfigTabLangValue {
            get {
                return ResourceManager.GetString("ConfigTabLangValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string ConfigTabOptionsCbHead {
            get {
                return ResourceManager.GetString("ConfigTabOptionsCbHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración del servidor.
        /// </summary>
        public static string ConfigTabServerConfigHeader {
            get {
                return ResourceManager.GetString("ConfigTabServerConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        public static string ConfigWindowChannelsBfDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeber audio.
        /// </summary>
        public static string ConfigWindowChannelsBfEmbedAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfEmbedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyer.
        /// </summary>
        public static string ConfigWindowChannelsBfKeyer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfKeyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio de keyer interno.
        /// </summary>
        public static string ConfigWindowChannelsBfKeyerAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfKeyerAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flujo SDI.
        /// </summary>
        public static string ConfigWindowChannelsBfSdiStream {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfSdiStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog.
        /// </summary>
        public static string ConfigWindowChannelsBfWatchdog {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración del canal.
        /// </summary>
        public static string ConfigWindowChannelsChannelConfigGbHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelConfigGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal {0}.
        /// </summary>
        public static string ConfigWindowChannelsChannelListItemDisplay {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelListItemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canales.
        /// </summary>
        public static string ConfigWindowChannelsChannels {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de video.
        /// </summary>
        public static string ConfigWindowChannelsChannelVideoMode {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de la salida.
        /// </summary>
        public static string ConfigWindowChannelsConsumerConfigGbHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerConfigGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salidas.
        /// </summary>
        public static string ConfigWindowChannelsConsumers {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del buffer.
        /// </summary>
        public static string ConfigWindowChannelsDlBuffer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        public static string ConfigWindowChannelsDlDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeber audio.
        /// </summary>
        public static string ConfigWindowChannelsDlEmbedAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlEmbedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo de alfa.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyer.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo alfa.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latencia.
        /// </summary>
        public static string ConfigWindowChannelsDlLatency {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumentos.
        /// </summary>
        public static string ConfigWindowChannelsFfArgs {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsFfArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        public static string ConfigWindowChannelsFfPath {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsFfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canales.
        /// </summary>
        public static string ConfigWindowChannelsHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta salida no tiene opciones configurables.
        /// </summary>
        public static string ConfigWindowChannelsNiNoOptions {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNiNoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar campos.
        /// </summary>
        public static string ConfigWindowChannelsNnAllowFields {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNnAllowFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ConfigWindowChannelsNnName {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canales.
        /// </summary>
        public static string ConfigWindowChannelsSaChannelLayout {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsSaChannelLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latencia.
        /// </summary>
        public static string ConfigWindowChannelsSaLatency {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsSaLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siempre encima.
        /// </summary>
        public static string ConfigWindowChannelsScAlwaysOn {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScAlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación de aspecto.
        /// </summary>
        public static string ConfigWindowChannelsScAspect {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin bordes.
        /// </summary>
        public static string ConfigWindowChannelsScBorderless {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio de color.
        /// </summary>
        public static string ConfigWindowChannelsScColourSpace {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScColourSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        public static string ConfigWindowChannelsScDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        public static string ConfigWindowChannelsScHeight {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactiva.
        /// </summary>
        public static string ConfigWindowChannelsScInteractive {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo alfa.
        /// </summary>
        public static string ConfigWindowChannelsScKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfa lado a lado.
        /// </summary>
        public static string ConfigWindowChannelsScSbsKey {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScSbsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estirar.
        /// </summary>
        public static string ConfigWindowChannelsScStretch {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsync.
        /// </summary>
        public static string ConfigWindowChannelsScVsync {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScVsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        public static string ConfigWindowChannelsScWidth {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo ventana.
        /// </summary>
        public static string ConfigWindowChannelsScWindowed {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición X.
        /// </summary>
        public static string ConfigWindowChannelsScX {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición Y.
        /// </summary>
        public static string ConfigWindowChannelsScY {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMCP.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección escáner de medios.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpMediaHost {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpMediaHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto escáner de medios.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpMediaPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpMediaPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño del buffer.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashBuffer {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones del servidor.
        /// </summary>
        public static string ConfigWindowOptionsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto de depuración.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlDebugPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlDebugPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar GPU.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlEnableGpu {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlEnableGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string ConfigWindowOptionsTabLogGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.
        /// </summary>
        public static string ConfigWindowOptionsTabLogLogLevel {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga automática.
        /// </summary>
        public static string ConfigWindowOptionsTabNdiAutoload {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabNdiAutoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDI.
        /// </summary>
        public static string ConfigWindowOptionsTabNdiGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabNdiGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshabilitar clientes AMCP.
        /// </summary>
        public static string ConfigWindowOptionsTabOscAmcpDisable {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscAmcpDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto por defecto.
        /// </summary>
        public static string ConfigWindowOptionsTabOscDefaultPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscDefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC.
        /// </summary>
        public static string ConfigWindowOptionsTabOscGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredClientAddress {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredClientPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredClientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes predefinidos.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredefinedClients {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredefinedClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave de seguridad.
        /// </summary>
        public static string ConfigWindowOptionsTabPassGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPassGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string ConfigWindowOptionsTabPassValue {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPassValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de datos.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsDataPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de fuentes.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsFontPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsFontPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutas.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de registro.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsLogPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de medios.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsMediaPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsMediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta de plantillas.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsTemplatePath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ConfigWindowSaveButton {
            get {
                return ResourceManager.GetString("ConfigWindowSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar configuración del servidor.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar servidor.
        /// </summary>
        public static string ContextMenuCasparItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuCasparItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir ventana de diagnóstico.
        /// </summary>
        public static string ContextMenuDiagItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuDiagItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string ContextMenuExitItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExitItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconstruir medios.
        /// </summary>
        public static string ContextMenuRebuildMediaDbItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuRebuildMediaDbItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar escáner de medios.
        /// </summary>
        public static string ContextMenuScannerItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuScannerItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida Decklink.
        /// </summary>
        public static string DecklinkConsumer {
            get {
                return ResourceManager.GetString("DecklinkConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar ejecutable.
        /// </summary>
        public static string DeleteExecutablePromptCaption {
            get {
                return ResourceManager.GetString("DeleteExecutablePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguro desea eliminar el ejecutable? (no se puede deshacer).
        /// </summary>
        public static string DeleteExecutablePromptMessage {
            get {
                return ResourceManager.GetString("DeleteExecutablePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumentos.
        /// </summary>
        public static string ExecutableConfigWindowArgs {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoejecutar.
        /// </summary>
        public static string ExecutableConfigWindowAuto {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar automáticamente al iniciar la aplicación.
        /// </summary>
        public static string ExecutableConfigWindowAutoDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowAutoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comandos de inicio.
        /// </summary>
        public static string ExecutableConfigWindowCommands {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retardo entre comandos.
        /// </summary>
        public static string ExecutableConfigWindowCommandsDelay {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de pausa entre cada comando de inicio (milisegundos).
        /// </summary>
        public static string ExecutableConfigWindowCommandsDelayDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando.
        /// </summary>
        public static string ExecutableConfigWindowCommandsDgHeader {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar comandos.
        /// </summary>
        public static string ExecutableConfigWindowCommandsEnabled {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilita el envío de comandos al ejecutable en la consola.
        /// </summary>
        public static string ExecutableConfigWindowCommandsEnabledDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retardo de inicio.
        /// </summary>
        public static string ExecutableConfigWindowDelay {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de espera antes de la ejecución (milisegundos).
        /// </summary>
        public static string ExecutableConfigWindowDelayDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Múltiples instancias.
        /// </summary>
        public static string ExecutableConfigWindowMultipleInstancesEnabled {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowMultipleInstancesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite la ejecución de múltiples procesos con el mismo nombre (CasparCG.exe permite diferentes archivos de configuración especificando la ruta en el campo argumentos).
        /// </summary>
        public static string ExecutableConfigWindowMultipleInstancesEnabledDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowMultipleInstancesEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ExecutableConfigWindowName {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta del ejecutable.
        /// </summary>
        public static string ExecutableConfigWindowPath {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración del ejecutable.
        /// </summary>
        public static string ExecutableConfigWindowTitle {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación del ejecutable incorrecta.
        /// </summary>
        public static string ExecutableNotFoundWarningCaption {
            get {
                return ResourceManager.GetString("ExecutableNotFoundWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compruebe la ruta del ejecutable.
        /// </summary>
        public static string ExecutableNotFoundWarningMessage {
            get {
                return ResourceManager.GetString("ExecutableNotFoundWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida FFmpeg.
        /// </summary>
        public static string FFConsumer {
            get {
                return ResourceManager.GetString("FFConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutables.
        /// </summary>
        public static string FileDialogFilterDescription {
            get {
                return ResourceManager.GetString("FileDialogFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida iVGA.
        /// </summary>
        public static string IvgaConsumer {
            get {
                return ResourceManager.GetString("IvgaConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida NDI.
        /// </summary>
        public static string NdiConsumer {
            get {
                return ResourceManager.GetString("NdiConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo ejecutable.
        /// </summary>
        public static string NewExecutableName {
            get {
                return ResourceManager.GetString("NewExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar archivo.
        /// </summary>
        public static string OpenConfigEditorEditButtonText {
            get {
                return ResourceManager.GetString("OpenConfigEditorEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo archivo.
        /// </summary>
        public static string OpenConfigEditorNewButtonText {
            get {
                return ResourceManager.GetString("OpenConfigEditorNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida a Pantalla.
        /// </summary>
        public static string ScreenConsumer {
            get {
                return ResourceManager.GetString("ScreenConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string StatusTabHeader {
            get {
                return ResourceManager.GetString("StatusTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida a Audio de Sistema.
        /// </summary>
        public static string SystemAudioConsumer {
            get {
                return ResourceManager.GetString("SystemAudioConsumer", resourceCulture);
            }
        }
    }
}
