//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasparLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasparLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        ///
        ///You should have received a copy  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutWindowNotice {
            get {
                return ResourceManager.GetString("AboutWindowNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend app for CasparCG server.
        /// </summary>
        public static string AboutWindowTagline {
            get {
                return ResourceManager.GetString("AboutWindowTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutWindowVersion {
            get {
                return ResourceManager.GetString("AboutWindowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Launcher.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtNet consumer.
        /// </summary>
        public static string ArtnetConsumer {
            get {
                return ResourceManager.GetString("ArtnetConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimmer.
        /// </summary>
        public static string ArtnetFixtureType_DIMMER {
            get {
                return ResourceManager.GetString("ArtnetFixtureType_DIMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string ArtnetFixtureType_RGB {
            get {
                return ResourceManager.GetString("ArtnetFixtureType_RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGBW.
        /// </summary>
        public static string ArtnetFixtureType_RGBW {
            get {
                return ResourceManager.GetString("ArtnetFixtureType_RGBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluefish consumer.
        /// </summary>
        public static string BluefishConsumer {
            get {
                return ResourceManager.GetString("BluefishConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string BluefishKeyer_Disabled {
            get {
                return ResourceManager.GetString("BluefishKeyer_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string BluefishKeyer_External {
            get {
                return ResourceManager.GetString("BluefishKeyer_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string BluefishKeyer_Internal {
            get {
                return ResourceManager.GetString("BluefishKeyer_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDI video input.
        /// </summary>
        public static string BluefishKeyerAudio_Input {
            get {
                return ResourceManager.GetString("BluefishKeyerAudio_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video output channel.
        /// </summary>
        public static string BluefishKeyerAudio_Output {
            get {
                return ResourceManager.GetString("BluefishKeyerAudio_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string BluefishUhdMode_Auto {
            get {
                return ResourceManager.GetString("BluefishUhdMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable BVC-Multi_Link.
        /// </summary>
        public static string BluefishUhdMode_DisableBVC {
            get {
                return ResourceManager.GetString("BluefishUhdMode_DisableBVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force 2SI output.
        /// </summary>
        public static string BluefishUhdMode_Force2SI {
            get {
                return ResourceManager.GetString("BluefishUhdMode_Force2SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force SQ output.
        /// </summary>
        public static string BluefishUhdMode_ForceSQ {
            get {
                return ResourceManager.GetString("BluefishUhdMode_ForceSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseForFileButton {
            get {
                return ResourceManager.GetString("BrowseForFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick folder....
        /// </summary>
        public static string BrowseForPathButton {
            get {
                return ResourceManager.GetString("BrowseForPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick path for the &apos;{0}&apos; folder.
        /// </summary>
        public static string BrowseForPathDialogCaption {
            get {
                return ResourceManager.GetString("BrowseForPathDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string ClosePromptCaption {
            get {
                return ResourceManager.GetString("ClosePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app keeps all the server components running.
        ///Closing it will end all server services.
        ///Do you want to continue?.
        /// </summary>
        public static string ClosePromptMessage {
            get {
                return ResourceManager.GetString("ClosePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console buffer.
        /// </summary>
        public static string ConfigBufferLines {
            get {
                return ResourceManager.GetString("ConfigBufferLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files.
        /// </summary>
        public static string ConfigFileDialogFilterDescription {
            get {
                return ResourceManager.GetString("ConfigFileDialogFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file.
        /// </summary>
        public static string ConfigFileText {
            get {
                return ResourceManager.GetString("ConfigFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore console empty lines.
        /// </summary>
        public static string ConfigSupressEmptyLines {
            get {
                return ResourceManager.GetString("ConfigSupressEmptyLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ConfigTabAboutGb {
            get {
                return ResourceManager.GetString("ConfigTabAboutGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CasparCG Server is a Windows and Linux software used to play out professional graphics, audio and video to multiple outputs as a layerbased real-time compositor. It has been in 24/7 broadcast production since 2006. And the best, it&apos;s free. Used by most broadcasters in Europe.
        ///More info at:.
        /// </summary>
        public static string ConfigTabAboutProjectDescription {
            get {
                return ResourceManager.GetString("ConfigTabAboutProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CasparCG project.
        /// </summary>
        public static string ConfigTabAboutProjectName {
            get {
                return ResourceManager.GetString("ConfigTabAboutProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit a different file than &apos;casparcg.config&apos;, hold the Shift key while clicking the &apos;Edit file&apos; button.
        /// </summary>
        public static string ConfigTabEditConfigFilesDesc {
            get {
                return ResourceManager.GetString("ConfigTabEditConfigFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables.
        /// </summary>
        public static string ConfigTabExecGbHeader {
            get {
                return ResourceManager.GetString("ConfigTabExecGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ConfigTabOptionsCbHead {
            get {
                return ResourceManager.GetString("ConfigTabOptionsCbHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server configuration.
        /// </summary>
        public static string ConfigTabServerConfigHeader {
            get {
                return ResourceManager.GetString("ConfigTabServerConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fixture.
        /// </summary>
        public static string ConfigWindowChannelsAnAddFixture {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnAddFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureChannels {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture count.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureCount {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureHeight {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureRotation {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtures {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start address.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureStart {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureType {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureWidth {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureX {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y position.
        /// </summary>
        public static string ConfigWindowChannelsAnFixtureY {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnFixtureY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ConfigWindowChannelsAnHost {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConfigWindowChannelsAnPort {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh rate.
        /// </summary>
        public static string ConfigWindowChannelsAnRate {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universe.
        /// </summary>
        public static string ConfigWindowChannelsAnUniverse {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsAnUniverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string ConfigWindowChannelsBfDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded audio.
        /// </summary>
        public static string ConfigWindowChannelsBfEmbedAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfEmbedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyer.
        /// </summary>
        public static string ConfigWindowChannelsBfKeyer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfKeyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal keyer audio source.
        /// </summary>
        public static string ConfigWindowChannelsBfKeyerAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfKeyerAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDI stream.
        /// </summary>
        public static string ConfigWindowChannelsBfSdiStream {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfSdiStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UHD mode.
        /// </summary>
        public static string ConfigWindowChannelsBfUhdMode {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfUhdMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog.
        /// </summary>
        public static string ConfigWindowChannelsBfWatchdog {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsBfWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel settings.
        /// </summary>
        public static string ConfigWindowChannelsChannelConfigGbHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelConfigGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel {0}.
        /// </summary>
        public static string ConfigWindowChannelsChannelListItemDisplay {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelListItemDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string ConfigWindowChannelsChannelProducerLayer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelProducerLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string ConfigWindowChannelsChannelProducerMedia {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelProducerMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producers.
        /// </summary>
        public static string ConfigWindowChannelsChannelProducers {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelProducers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string ConfigWindowChannelsChannels {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video mode.
        /// </summary>
        public static string ConfigWindowChannelsChannelVideoMode {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsChannelVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel video mode.
        /// </summary>
        public static string ConfigWindowChannelsConsumerChannelVideoMode {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerChannelVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer settings.
        /// </summary>
        public static string ConfigWindowChannelsConsumerConfigGbHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerConfigGbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumers.
        /// </summary>
        public static string ConfigWindowChannelsConsumers {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination X.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionDestX {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionDestX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Y.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionDestY {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionDestY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable subregion.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionEnable {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionHeight {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source X.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionSrcX {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionSrcX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Y.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionSrcY {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionSrcY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ConfigWindowChannelsConsumerSubregionWidth {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerSubregionWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video mode.
        /// </summary>
        public static string ConfigWindowChannelsConsumerVideoMode {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsConsumerVideoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add port.
        /// </summary>
        public static string ConfigWindowChannelsDlAddPort {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlAddPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer depth.
        /// </summary>
        public static string ConfigWindowChannelsDlBuffer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string ConfigWindowChannelsDlDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeded audio.
        /// </summary>
        public static string ConfigWindowChannelsDlEmbedAudio {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlEmbedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key device.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyer.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyer {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key only.
        /// </summary>
        public static string ConfigWindowChannelsDlKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency.
        /// </summary>
        public static string ConfigWindowChannelsDlLatency {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string ConfigWindowChannelsDlPortDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlPortDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key only.
        /// </summary>
        public static string ConfigWindowChannelsDlPortKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlPortKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional synced ports.
        /// </summary>
        public static string ConfigWindowChannelsDlPorts {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for reference.
        /// </summary>
        public static string ConfigWindowChannelsDlWaitForReference {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlWaitForReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for reference duration.
        /// </summary>
        public static string ConfigWindowChannelsDlWaitForReferenceDuration {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlWaitForReferenceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (time in seconds).
        /// </summary>
        public static string ConfigWindowChannelsDlWaitForReferenceDurationDetail {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsDlWaitForReferenceDurationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string ConfigWindowChannelsFfArgs {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsFfArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ConfigWindowChannelsFfPath {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsFfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string ConfigWindowChannelsHeader {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This consumer has no settings.
        /// </summary>
        public static string ConfigWindowChannelsNiNoOptions {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNiNoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow fields.
        /// </summary>
        public static string ConfigWindowChannelsNnAllowFields {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNnAllowFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigWindowChannelsNnName {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsNnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel layout.
        /// </summary>
        public static string ConfigWindowChannelsSaChannelLayout {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsSaChannelLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency.
        /// </summary>
        public static string ConfigWindowChannelsSaLatency {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsSaLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string ConfigWindowChannelsScAlwaysOn {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScAlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio.
        /// </summary>
        public static string ConfigWindowChannelsScAspect {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless.
        /// </summary>
        public static string ConfigWindowChannelsScBorderless {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScBorderless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour space.
        /// </summary>
        public static string ConfigWindowChannelsScColourSpace {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScColourSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string ConfigWindowChannelsScDevice {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ConfigWindowChannelsScHeight {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive.
        /// </summary>
        public static string ConfigWindowChannelsScInteractive {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Only.
        /// </summary>
        public static string ConfigWindowChannelsScKeyOnly {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScKeyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigWindowChannelsScName {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side by side key.
        /// </summary>
        public static string ConfigWindowChannelsScSbsKey {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScSbsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ConfigWindowChannelsScStretch {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsync.
        /// </summary>
        public static string ConfigWindowChannelsScVsync {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScVsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ConfigWindowChannelsScWidth {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string ConfigWindowChannelsScWindowed {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScWindowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position.
        /// </summary>
        public static string ConfigWindowChannelsScX {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y position.
        /// </summary>
        public static string ConfigWindowChannelsScY {
            get {
                return ResourceManager.GetString("ConfigWindowChannelsScY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMCP.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media scanner host.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpMediaHost {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpMediaHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media scanner port.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpMediaPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpMediaPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConfigWindowOptionsTabAmcpPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAmcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default output device.
        /// </summary>
        public static string ConfigWindowOptionsTabAudioDefaultDevice {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAudioDefaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string ConfigWindowOptionsTabAudioGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabAudioGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinterlace.
        /// </summary>
        public static string ConfigWindowOptionsTabFfmpegDeinterlace {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFfmpegDeinterlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg.
        /// </summary>
        public static string ConfigWindowOptionsTabFfmpegGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFfmpegGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU threads.
        /// </summary>
        public static string ConfigWindowOptionsTabFfmpegThreads {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFfmpegThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer depth.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashBuffer {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Producer.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashEnableProducer {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashEnableProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string ConfigWindowOptionsTabFlashGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabFlashGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server options.
        /// </summary>
        public static string ConfigWindowOptionsTabHeader {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGLE graphics backend.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlAngleBackend {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlAngleBackend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging port.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlDebugPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlDebugPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPU.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlEnableGpu {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlEnableGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string ConfigWindowOptionsTabHtmlGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabHtmlGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable column alignment.
        /// </summary>
        public static string ConfigWindowOptionsTabLogDisableColumnAlignment {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogDisableColumnAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is supported for compatibility purposes. It does not affect the behavior in this launcher&apos;s console..
        /// </summary>
        public static string ConfigWindowOptionsTabLogDisableColumnAlignmentNotice {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogDisableColumnAlignmentNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string ConfigWindowOptionsTabLogGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ConfigWindowOptionsTabLogLogLevel {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable logging to file.
        /// </summary>
        public static string ConfigWindowOptionsTabLogLogToFile {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabLogLogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoload.
        /// </summary>
        public static string ConfigWindowOptionsTabNdiAutoload {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabNdiAutoload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDI.
        /// </summary>
        public static string ConfigWindowOptionsTabNdiGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabNdiGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable send to AMCP clients.
        /// </summary>
        public static string ConfigWindowOptionsTabOscAmcpDisable {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscAmcpDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default port.
        /// </summary>
        public static string ConfigWindowOptionsTabOscDefaultPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscDefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC.
        /// </summary>
        public static string ConfigWindowOptionsTabOscGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredClientAddress {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredClientPort {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredClientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined clients.
        /// </summary>
        public static string ConfigWindowOptionsTabOscPredefinedClients {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabOscPredefinedClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear passphrase.
        /// </summary>
        public static string ConfigWindowOptionsTabPassGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPassGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ConfigWindowOptionsTabPassValue {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPassValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data path.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsDataPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font path.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsFontPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsFontPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsGb {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log path.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsLogPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsLogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media path.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsMediaPath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsMediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template path.
        /// </summary>
        public static string ConfigWindowOptionsTabPathsTemplatePath {
            get {
                return ResourceManager.GetString("ConfigWindowOptionsTabPathsTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConfigWindowSaveButton {
            get {
                return ResourceManager.GetString("ConfigWindowSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has ocurred.
        /// </summary>
        public static string ConfigWindowStatusMessageSaveError {
            get {
                return ResourceManager.GetString("ConfigWindowStatusMessageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to the file.
        /// </summary>
        public static string ConfigWindowStatusMessageSaveIOError {
            get {
                return ResourceManager.GetString("ConfigWindowStatusMessageSaveIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been saved successfully.
        /// </summary>
        public static string ConfigWindowStatusMessageSaveSuccess {
            get {
                return ResourceManager.GetString("ConfigWindowStatusMessageSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit server configuration.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadence.
        /// </summary>
        public static string ConfigWindowVideoModesCadence {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesCadence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom video mode.
        /// </summary>
        public static string ConfigWindowVideoModesCustomVideoModeGb {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesCustomVideoModeGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom video modes.
        /// </summary>
        public static string ConfigWindowVideoModesCustomVideoModes {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesCustomVideoModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ConfigWindowVideoModesDuration {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ConfigWindowVideoModesHeight {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video mode ID.
        /// </summary>
        public static string ConfigWindowVideoModesId {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewVideoMode.
        /// </summary>
        public static string ConfigWindowVideoModesNewModeId {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesNewModeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video modes.
        /// </summary>
        public static string ConfigWindowVideoModesTab {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time scale.
        /// </summary>
        public static string ConfigWindowVideoModesTimeScale {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesTimeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ConfigWindowVideoModesWidth {
            get {
                return ResourceManager.GetString("ConfigWindowVideoModesWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ContextMenuExecConfigItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExecConfigItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open diagnostics window.
        /// </summary>
        public static string ContextMenuExecDiagItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExecDiagItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open channel grid window.
        /// </summary>
        public static string ContextMenuExecGridItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExecGridItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string ContextMenuExecRestartItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExecRestartItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ContextMenuExecStartItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExecStartItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ContextMenuExecStopItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExecStopItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ContextMenuExitItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuExitItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild media database.
        /// </summary>
        public static string ContextMenuRebuildMediaDbItemHeader {
            get {
                return ResourceManager.GetString("ContextMenuRebuildMediaDbItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart all.
        /// </summary>
        public static string ContextMenuRestartAllHeader {
            get {
                return ResourceManager.GetString("ContextMenuRestartAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all.
        /// </summary>
        public static string ContextMenuStartAllHeader {
            get {
                return ResourceManager.GetString("ContextMenuStartAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all.
        /// </summary>
        public static string ContextMenuStopAllHeader {
            get {
                return ResourceManager.GetString("ContextMenuStopAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string CreateConfigFileErrorCaption {
            get {
                return ResourceManager.GetString("CreateConfigFileErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the configuration file.
        ///Could not write the file to disk..
        /// </summary>
        public static string CreateConfigFileIOError {
            get {
                return ResourceManager.GetString("CreateConfigFileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decklink consumer.
        /// </summary>
        public static string DecklinkConsumer {
            get {
                return ResourceManager.GetString("DecklinkConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DecklinkKeyer_Default {
            get {
                return ResourceManager.GetString("DecklinkKeyer_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string DecklinkKeyer_External {
            get {
                return ResourceManager.GetString("DecklinkKeyer_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External (separate device).
        /// </summary>
        public static string DecklinkKeyer_ExternalSeparateDevice {
            get {
                return ResourceManager.GetString("DecklinkKeyer_ExternalSeparateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string DecklinkKeyer_Internal {
            get {
                return ResourceManager.GetString("DecklinkKeyer_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DecklinkLatency_Default {
            get {
                return ResourceManager.GetString("DecklinkLatency_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string DecklinkLatency_Low {
            get {
                return ResourceManager.GetString("DecklinkLatency_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string DecklinkLatency_Normal {
            get {
                return ResourceManager.GetString("DecklinkLatency_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string DecklinkWaitForReference_Auto {
            get {
                return ResourceManager.GetString("DecklinkWaitForReference_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string DecklinkWaitForReference_Disable {
            get {
                return ResourceManager.GetString("DecklinkWaitForReference_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string DecklinkWaitForReference_Enable {
            get {
                return ResourceManager.GetString("DecklinkWaitForReference_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the configuration file.
        ///Unknown error..
        /// </summary>
        public static string DeleteConfigFileError {
            get {
                return ResourceManager.GetString("DeleteConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DeleteConfigFileErrorCaption {
            get {
                return ResourceManager.GetString("DeleteConfigFileErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the configuration file.
        ///Write error..
        /// </summary>
        public static string DeleteConfigFileIOError {
            get {
                return ResourceManager.GetString("DeleteConfigFileIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete executable.
        /// </summary>
        public static string DeleteExecutablePromptCaption {
            get {
                return ResourceManager.GetString("DeleteExecutablePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the executable? (this can&apos;t be undone).
        /// </summary>
        public static string DeleteExecutablePromptMessage {
            get {
                return ResourceManager.GetString("DeleteExecutablePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string ExecutableConfigWindowArgs {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string ExecutableConfigWindowAuto {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch automatically on startup.
        /// </summary>
        public static string ExecutableConfigWindowAutoDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowAutoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup commands.
        /// </summary>
        public static string ExecutableConfigWindowCommands {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between commands.
        /// </summary>
        public static string ExecutableConfigWindowCommandsDelay {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time between each startup command (milliseconds).
        /// </summary>
        public static string ExecutableConfigWindowCommandsDelayDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string ExecutableConfigWindowCommandsDgHeader {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsDgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable commands.
        /// </summary>
        public static string ExecutableConfigWindowCommandsEnabled {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables writing commands to the console.
        /// </summary>
        public static string ExecutableConfigWindowCommandsEnabledDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        public static string ExecutableConfigWindowCommandsExport {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        public static string ExecutableConfigWindowCommandsImport {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowCommandsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file.
        /// </summary>
        public static string ExecutableConfigWindowConfigFile {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup delay.
        /// </summary>
        public static string ExecutableConfigWindowDelay {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time before launch (milliseconds).
        /// </summary>
        public static string ExecutableConfigWindowDelayDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete executable.
        /// </summary>
        public static string ExecutableConfigWindowDeleteButton {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete configuration file.
        /// </summary>
        public static string ExecutableConfigWindowDeleteFilePromptCaption {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDeleteFilePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the configuration file &apos;{0}&apos;?
        ///The file will be deleted permanently..
        /// </summary>
        public static string ExecutableConfigWindowDeleteFilePromptMessage {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowDeleteFilePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable options.
        /// </summary>
        public static string ExecutableConfigWindowGbOptionsHeader {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowGbOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill current path only.
        /// </summary>
        public static string ExecutableConfigWindowKillOnlyCurrentPathEnabled {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowKillOnlyCurrentPathEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, only processes runnning on the same path are killed. Otherwise, any process with the same name will be terminated..
        /// </summary>
        public static string ExecutableConfigWindowKillOnlyCurrentPathEnabledDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowKillOnlyCurrentPathEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple instances.
        /// </summary>
        public static string ExecutableConfigWindowMultipleInstancesEnabled {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowMultipleInstancesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables running multiple processes with the same name (CasparCG.exe allows different config files specifying its path in the arguments field).
        /// </summary>
        public static string ExecutableConfigWindowMultipleInstancesEnabledDesc {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowMultipleInstancesEnabledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ExecutableConfigWindowName {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string ExecutableConfigWindowPath {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable configuration.
        /// </summary>
        public static string ExecutableConfigWindowTitle {
            get {
                return ResourceManager.GetString("ExecutableConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting the process.
        /// </summary>
        public static string ExecutableErrorMessage {
            get {
                return ResourceManager.GetString("ExecutableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong path.
        /// </summary>
        public static string ExecutableNotFoundWarningCaption {
            get {
                return ResourceManager.GetString("ExecutableNotFoundWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check executable file path.
        /// </summary>
        public static string ExecutableNotFoundWarningMessage {
            get {
                return ResourceManager.GetString("ExecutableNotFoundWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has been started successfully.
        /// </summary>
        public static string ExecutableStartedMessage {
            get {
                return ResourceManager.GetString("ExecutableStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has stopped.
        /// </summary>
        public static string ExecutableStoppedMessage {
            get {
                return ResourceManager.GetString("ExecutableStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong executable path.
        /// </summary>
        public static string ExecutableTabNotFoundCaption {
            get {
                return ResourceManager.GetString("ExecutableTabNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the correct path in the executable&apos;s configuration window.
        /// </summary>
        public static string ExecutableTabNotFoundMessage {
            get {
                return ResourceManager.GetString("ExecutableTabNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration.
        /// </summary>
        public static string ExecutableTabOpenConfigButton {
            get {
                return ResourceManager.GetString("ExecutableTabOpenConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Export Location.
        /// </summary>
        public static string ExportCommandsDialogTitle {
            get {
                return ResourceManager.GetString("ExportCommandsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg consumer.
        /// </summary>
        public static string FFConsumer {
            get {
                return ResourceManager.GetString("FFConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FfmpegDeinterlace_All {
            get {
                return ResourceManager.GetString("FfmpegDeinterlace_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlaced.
        /// </summary>
        public static string FfmpegDeinterlace_Interlaced {
            get {
                return ResourceManager.GetString("FfmpegDeinterlace_Interlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FfmpegDeinterlace_None {
            get {
                return ResourceManager.GetString("FfmpegDeinterlace_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables.
        /// </summary>
        public static string FileDialogFilterDescription {
            get {
                return ResourceManager.GetString("FileDialogFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D3D11.
        /// </summary>
        public static string HtmlAngleGraphicsBackend_D3D11 {
            get {
                return ResourceManager.GetString("HtmlAngleGraphicsBackend_D3D11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D3D9.
        /// </summary>
        public static string HtmlAngleGraphicsBackend_D3D9 {
            get {
                return ResourceManager.GetString("HtmlAngleGraphicsBackend_D3D9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenGL.
        /// </summary>
        public static string HtmlAngleGraphicsBackend_OpenGL {
            get {
                return ResourceManager.GetString("HtmlAngleGraphicsBackend_OpenGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File With Commands.
        /// </summary>
        public static string ImportCommandsDialogTitle {
            get {
                return ResourceManager.GetString("ImportCommandsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVGA consumer.
        /// </summary>
        public static string IvgaConsumer {
            get {
                return ResourceManager.GetString("IvgaConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string LanguagesDefault {
            get {
                return ResourceManager.GetString("LanguagesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguagesEnglish {
            get {
                return ResourceManager.GetString("LanguagesEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string LanguagesEspañol {
            get {
                return ResourceManager.GetString("LanguagesEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LogLevel_Debug {
            get {
                return ResourceManager.GetString("LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LogLevel_Error {
            get {
                return ResourceManager.GetString("LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string LogLevel_Fatal {
            get {
                return ResourceManager.GetString("LogLevel_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LogLevel_Info {
            get {
                return ResourceManager.GetString("LogLevel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        public static string LogLevel_Trace {
            get {
                return ResourceManager.GetString("LogLevel_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LogLevel_Warning {
            get {
                return ResourceManager.GetString("LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string MenuBarHelpAbout {
            get {
                return ResourceManager.GetString("MenuBarHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CasparCG porject.
        /// </summary>
        public static string MenuBarHelpCasparCGProject {
            get {
                return ResourceManager.GetString("MenuBarHelpCasparCGProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuBarHelpMenuHeader {
            get {
                return ResourceManager.GetString("MenuBarHelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string MenuBarHelpReportIssue {
            get {
                return ResourceManager.GetString("MenuBarHelpReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuBarOptionsLanguage {
            get {
                return ResourceManager.GetString("MenuBarOptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuBarOptionsMenuHeader {
            get {
                return ResourceManager.GetString("MenuBarOptionsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string MenuBarOptionsNotifications {
            get {
                return ResourceManager.GetString("MenuBarOptionsNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process errors.
        /// </summary>
        public static string MenuBarOptionsNotificationsErrors {
            get {
                return ResourceManager.GetString("MenuBarOptionsNotificationsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process started.
        /// </summary>
        public static string MenuBarOptionsNotificationsStarted {
            get {
                return ResourceManager.GetString("MenuBarOptionsNotificationsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process stopped.
        /// </summary>
        public static string MenuBarOptionsNotificationsStopped {
            get {
                return ResourceManager.GetString("MenuBarOptionsNotificationsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open at login.
        /// </summary>
        public static string MenuBarOptionsOpenAtLogin {
            get {
                return ResourceManager.GetString("MenuBarOptionsOpenAtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop console lines.
        /// </summary>
        public static string MenuBarViewCropLines {
            get {
                return ResourceManager.GetString("MenuBarViewCropLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string MenuBarViewDarkMode {
            get {
                return ResourceManager.GetString("MenuBarViewDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuBarViewMenuHeader {
            get {
                return ResourceManager.GetString("MenuBarViewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylize console.
        /// </summary>
        public static string MenuBarViewStylizeConsole {
            get {
                return ResourceManager.GetString("MenuBarViewStylizeConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDI consumer.
        /// </summary>
        public static string NdiConsumer {
            get {
                return ResourceManager.GetString("NdiConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New executable.
        /// </summary>
        public static string NewExecutableName {
            get {
                return ResourceManager.GetString("NewExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not running.
        /// </summary>
        public static string NotRunning {
            get {
                return ResourceManager.GetString("NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit file.
        /// </summary>
        public static string OpenConfigEditorEditButtonText {
            get {
                return ResourceManager.GetString("OpenConfigEditorEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string OpenConfigEditorErrorCaption {
            get {
                return ResourceManager.GetString("OpenConfigEditorErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file is malformed.
        /// </summary>
        public static string OpenConfigEditorFileError {
            get {
                return ResourceManager.GetString("OpenConfigEditorFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the configuration file.
        /// </summary>
        public static string OpenConfigEditorIOError {
            get {
                return ResourceManager.GetString("OpenConfigEditorIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string OpenConfigEditorNewButtonText {
            get {
                return ResourceManager.GetString("OpenConfigEditorNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:9.
        /// </summary>
        public static string ScreenAspectRatio_16_9 {
            get {
                return ResourceManager.GetString("ScreenAspectRatio_16:9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:3.
        /// </summary>
        public static string ScreenAspectRatio_4_3 {
            get {
                return ResourceManager.GetString("ScreenAspectRatio_4:3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ScreenAspectRatio_Default {
            get {
                return ResourceManager.GetString("ScreenAspectRatio_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataVideo (Full).
        /// </summary>
        public static string ScreenColourSpace_DataVideo_Full {
            get {
                return ResourceManager.GetString("ScreenColourSpace_DataVideo_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataVideo (Limited).
        /// </summary>
        public static string ScreenColourSpace_DataVideo_Limited {
            get {
                return ResourceManager.GetString("ScreenColourSpace_DataVideo_Limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string ScreenColourSpace_RGB {
            get {
                return ResourceManager.GetString("ScreenColourSpace_RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen consumer.
        /// </summary>
        public static string ScreenConsumer {
            get {
                return ResourceManager.GetString("ScreenConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string ScreenStretch_Fill {
            get {
                return ResourceManager.GetString("ScreenStretch_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ScreenStretch_None {
            get {
                return ResourceManager.GetString("ScreenStretch_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string ScreenStretch_Uniform {
            get {
                return ResourceManager.GetString("ScreenStretch_Uniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform to fill.
        /// </summary>
        public static string ScreenStretch_UniformToFill {
            get {
                return ResourceManager.GetString("ScreenStretch_UniformToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusTabHeader {
            get {
                return ResourceManager.GetString("StatusTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string SystemAudioChannelLayout_Matrix {
            get {
                return ResourceManager.GetString("SystemAudioChannelLayout_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        public static string SystemAudioChannelLayout_Mono {
            get {
                return ResourceManager.GetString("SystemAudioChannelLayout_Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereo.
        /// </summary>
        public static string SystemAudioChannelLayout_Stereo {
            get {
                return ResourceManager.GetString("SystemAudioChannelLayout_Stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Audio consumer.
        /// </summary>
        public static string SystemAudioConsumer {
            get {
                return ResourceManager.GetString("SystemAudioConsumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%d} days, .
        /// </summary>
        public static string UptimeDaysFormat {
            get {
                return ResourceManager.GetString("UptimeDaysFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%h\:mm\:ss}.
        /// </summary>
        public static string UptimeTimeFormat {
            get {
                return ResourceManager.GetString("UptimeTimeFormat", resourceCulture);
            }
        }
    }
}
